routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [BlogController::class, 'index'])->name('blog');
Route::get('/article/{slug}', [BlogController::class, 'isi_blog'])->name('isi_blog');
Route::get('/search', [BlogController::class, 'cari'])->name('cari');



Auth::routes();

Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::get('/post/deleted', [PostController::class, 'delete_show'])->name('post.deleted');
    Route::get('/post/restore/{id}', [PostController::class, 'restore'])->name('post.restore');
    Route::delete('/post/delete-permanent/{id}', [PostController::class, 'kill'])->name('post.kill');

    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    Route::resource('user', UserController::class);
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/{slug}', [BlogController::class, 'kategori'])->name('kategori');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'posts';
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tags::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Post;
use Alert;
use App\Models\Tags;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Paginator::useBootstrap();
        $posts = Post::with(['category', 'user'])->latest()->paginate(10);

        return view('admin.post.index', compact('posts'))->with('i');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('name', 'ASC')->get();
        $tags = Tags::all();

        return view('admin.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'judul' => 'required|max:64|string',
            'category_id' => 'required',
            'content' => 'required',
            'gambar' => 'required|image|max:4096|mimes:png,jpg,svg,gif,jpeg',
            'slug' => 'string|max:64',
        ]);

        $gambar = $request->gambar;
        $namaGambar = time().".".$gambar->getClientOriginalExtension();

        $gambar->move(public_path().'/uploads/posts', $namaGambar);

        $slug = Str::slug($request->judul);
        $post = Post::create([
                'judul' => $request->judul,
                'category_id' => $request->category_id,
                'content' => $request->content,
                'gambar' => $namaGambar,
                'slug' => $slug,
                'user_id' => Auth::user()->id
            ]);

        $post->tags()->attach($request->tags);

        return redirect()->route('post.index')->withSuccess('Post successfully created !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $tags = Tags::all();
        $categories = Category::orderBy('name', 'ASC')->get();

        return view('admin.post.edit', compact('post', 'tags', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        $old_gambar = $post->gambar;
        $this->validate($request, [
            'judul' => 'required|max:64|string',
            'category_id' => 'required',
            'content' => 'required',
            'gambar' => 'image|max:4096|mimes:png,jpg,svg,gif,jpeg',
            'slug' => 'string|max:64'
        ]);

        //Cek apakah author/admin ingin memperbarui gambar
        if($request->has('gambar'))
        {
            $request->gambar->move(public_path().'/uploads/posts', $old_gambar);

            $slug = Str::slug($request->judul);
            $post_data = [
                    'judul' => $request->judul,
                    'category_id' => $request->category_id,
                    'content' => $request->content,
                    'gambar' => $old_gambar,
                    'slug' => $slug,
                    'user_id' => Auth::user()->id
                ];
        } else //Jika author/admin tidak ingin memperbarui gambar maka gambar tidak diupdate ke database
        {
            $slug = Str::slug($request->judul);
            $post_data = [
                'judul' => $request->judul,
                'category_id' => $request->category_id,
                'content' => $request->content,
                'slug' => $slug,
                'user_id' => Auth::user()->id
            ];
        }

        $post->tags()->sync($request->tags);
        $post->update($post_data);

        return redirect()->route('post.index')->withSuccess('Post successfully updated !');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id);

        //Hapus Data Database
        $post->delete();

        return redirect()->route('post.index')->withSuccess('Post successfully deleted temporarily !');
    }

    public function delete_show()
    {
        $posts = Post::onlyTrashed()->latest()->paginate(10);

        return view('admin.post.delete', compact('posts'))->with('i');
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->where('id', $id)->first();
        $post->restore();

        return redirect()->route('post.deleted')->withSuccess('Post successfully restored !');
    }

    public function kill($id)
    {
        $post = Post::withTrashed()->where('id', $id)->first();
        //Cek jika ada gambar
        $file = public_path('/uploads/posts/').$post->gambar;
        if (file_exists($file))
        {
            //jika ada gambar maka hapus gambar
            @unlink($file);
        }
        $post->forceDelete();

        return redirect()->route('post.deleted')->withSuccess('Post successfully deleted permanently !');
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.admin')

@section('title', 'Post')

@section('header')
    <h1>Post</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>Add Post</h4>
          <div class="card-header-action">
            <a href="{{ route('post.index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Back</a>
          </div>
        </div>
        <div class="card-body p-0">
            @if($errors->any())
                <div class="alert alert-danger mx-3">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="mx-3 mt-2" action="{{ route('post.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="judul">Judul</label>
                    <input type="text" name="judul" id="judul" class="form-control" placeholder="Please Insert Judul" maxlength="64" required value="{{ old('judul') }}">
                </div>

                <div class="form-group">
                    <label for="category_id">Category</label>
                    <select class="form-control select2" name="category_id" id="category_id" required>
                        <option value="" selected disabled>-- Choose Category --</option>
                        @foreach ($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="tag_id">Tags</label>
                    <select class="form-control select2" name="tags[]" multiple="">
                        @foreach ($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea class="form-control" name="content" id="content" cols="30" rows="10" placeholder="Please Insert Content" required>{{ old('content') }}</textarea>
                </div>

                <div class="form-group">
                    <label for="gambar">Thumbnail</label>
                    <input type="file" name="gambar" id="gambar" class="form-control" required value="{{ old('gambar') }}">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Save Post</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <script>
        var options = {
          filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
          filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
          filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
          filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
        };
    </script>
    <script>
    CKEDITOR.replace('content', options);
    </script>
@endpush

resources/views/admin/post/delete.blade.php
@extends('layouts.admin')

@section('title', 'Post')

@section('header')
    <h1>Post</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>List Deleted Post</h4>
          <div class="card-header-action">
            <a href="{{ route('post.index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Back</a>
          </div>
        </div>
        <div class="card-body p-0">
          <div class="table-responsive table-invoice">
            <table class="table table-striped">
              <tr>
                <th>#</th>
                <th>Nama Post</th>
                <th>Slug Post</th>
                <th>Category</th>
                <th class="text-center">Tag</th>
                <th>Content</th>
                <th>Thumbnail</th>
                <th>Action</th>
              </tr>
              @forelse ($posts as $post)
              <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $post->judul }}</td>
                <td>{{ $post->slug }}</td>
                <td>{{ $post->category->name }}</td>
                <td>
                @foreach ($post->tags as $tag)
                    <ul>
                        <li>{{ $tag->name }}</li>
                    </ul>
                @endforeach
                </td>
                <td>{{ $post->content }}</td>
                <td><img src="{{ asset('uploads/posts/'.$post->gambar) }}" class="rounded img-thumbnail" width="300" alt="thumbnail"></td>
                <td>
                    <form action="{{ route('post.kill', $post->id) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <a href="{{ route('post.restore', $post->id) }}" class="btn btn-warning">Restore</a>
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure ?')">Delete</button>
                    </form>
                </td>
              </tr>
              @empty
              <tr>
                  <td colspan="12"><p class="text-center text-danger mt-3"><strong>Data Empty !</strong></p></td>
              </tr>
              @endforelse
            </table>
            {{ $posts->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    @include('sweetalert::alert')
    <script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>
@endpush

resources/views/admin/post/edit.blade.php
@extends('layouts.admin')

@section('title', 'Post')

@section('header')
    <h1>Post</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>Edit Post</h4>
          <div class="card-header-action">
            <a href="{{ route('post.index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Back</a>
          </div>
        </div>
        <div class="card-body p-0">
            @if($errors->any())
                <div class="alert alert-danger mx-3">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="mx-3 mt-2" action="{{ route('post.update', $post->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="judul">Judul</label>
                    <input type="text" name="judul" id="judul" class="form-control" placeholder="Please Insert Judul" maxlength="64" required value="{{ $post->judul }}">
                </div>

                <div class="form-group">
                    <label for="category_id">Category</label>
                    <select class="form-control select2" name="category_id" id="category_id" required>
                        @foreach ($categories as $category)
                        <option value="{{ $category->id }}" @if($category->id == $post->category_id) selected @endif>{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="tag_id">Tags</label>
                    <select class="form-control select2" name="tags[]" multiple="">
                        @foreach ($tags as $tag)
                        <option value="{{ $tag->id }}"
                            @foreach ($post->tags as $value)
                                @if($tag->id == $value->id) selected @endif
                            @endforeach>{{ $tag->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="deskripsi">Content</label>
                    <textarea class="form-control deskripsi" name="content" id="deskripsi" cols="30" rows="10" placeholder="Please Insert Content" required>{{ $post->content }}</textarea>
                </div>

                <div class="form-group">
                    <label for="gambar">Thumbnail</label>
                    <input type="file" name="gambar" id="gambar" class="form-control">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-warning">Update Post</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <script>
        var options = {
          filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
          filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
          filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
          filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
        };
    </script>
    <script>
        CKEDITOR.replace( 'deskripsi', options);
    </script>
@endpush

resources/views/admin/post/index.blade.php
@extends('layouts.admin')

@section('title', 'Post')

@section('header')
    <h1>Post</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>List Post</h4>
          <div class="card-header-action">
            <a href="{{ route('post.create') }}" class="btn btn-primary">Add Post <i class="fas fa-chevron-right"></i></a>
            <a href="{{ route('post.deleted') }}" class="btn btn-danger">Deleted Post <i class="fas fa-chevron-right"></i></a>
          </div>
        </div>
        <div class="card-body p-0">
          <div class="table-responsive table-invoice">
            <table class="table table-striped">
              <tr>
                <th>#</th>
                <th>Nama Post</th>
                <th>Slug Post</th>
                <th>Author</th>
                <th>Category</th>
                <th class="text-center">Tag</th>
                <th>Content</th>
                <th>Thumbnail</th>
                <th>Action</th>
              </tr>
              @forelse ($posts as $post)
              <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $post->judul }}</td>
                <td>{{ $post->slug }}</td>
                <td><strong>{{ $post->user->name }}</strong></td>
                <td>{{ $post->category->name }}</td>
                <td>
                @foreach ($post->tags as $tag)
                    <ul>
                        <h6><span class="badge badge-info">{{ $tag->name }}</span></h6>
                    </ul>
                @endforeach
                </td>
                <td>{!! Str::limit($post->content, 100) !!}</td>
                <td><img src="{{ asset('uploads/posts/'.$post->gambar) }}" class="rounded img-thumbnail my-2" width="300" alt="thumbnail"></td>
                <td>
                    <form class="d-flex" action="{{ route('post.destroy', $post->id) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <a href="{{ route('post.edit', $post->id) }}" class="btn btn-warning mr-2">Edit</a>
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure ?')">Delete</button>
                    </form>
                </td>
              </tr>
              @empty
              <tr>
                  <td colspan="12"><p class="text-center text-danger mt-3"><strong>Data Empty !</strong></p></td>
              </tr>
              @endforelse
            </table>
            {{ $posts->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    @include('sweetalert::alert')
    <script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>
@endpush