routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [BlogController::class, 'index'])->name('blog');
Route::get('/article/{slug}', [BlogController::class, 'isi_blog'])->name('isi_blog');
Route::get('/search', [BlogController::class, 'cari'])->name('cari');



Auth::routes();

Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::get('/post/deleted', [PostController::class, 'delete_show'])->name('post.deleted');
    Route::get('/post/restore/{id}', [PostController::class, 'restore'])->name('post.restore');
    Route::delete('/post/delete-permanent/{id}', [PostController::class, 'kill'])->name('post.kill');

    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    Route::resource('user', UserController::class);
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/{slug}', [BlogController::class, 'kategori'])->name('kategori');

app/Models/Tags.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tags extends Model
{
    use HasFactory;

    protected $table = 'tags';
    protected $guarded = [];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tags;
use Illuminate\Http\Request;
use Alert;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Str;

class TagController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Paginator::useBootstrap();
        $tags = Tags::latest()->paginate(10);

        return view('admin.tag.index', compact('tags'))->with('i');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $this->validate($request, [
            'name' => 'required|min:2|max:20|string|unique:tags',
            'slug' => 'string|max:20'
        ]);

        $data['slug'] = Str::slug($request->name);

        Tags::create($data);

        return redirect()->route('tag.index')->withSuccess('Tag successfully created !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function show(Tags $tags)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tags::findOrFail($id);

        return view('admin.tag.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tags::findOrFail($id);

        $data = $request->all();

        $this->validate($request, [
            'name' => 'required|max:20|min:2|string|unique:tags,name,'.$tag->id,
            'slug' => 'string|max:20'
        ]);

        $data['slug'] = Str::slug($request->name);

        $tag->update($data);

        return redirect()->route('tag.index')->withSuccess('Tag successfully updated !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tags::findOrFail($id);
        $tag->delete();

        return redirect()->route('tag.index')->withSuccess('Tag successfully deleted !');
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.admin')

@section('title', 'Tag')

@section('header')
    <h1>Tag</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>Add Tag</h4>
          <div class="card-header-action">
            <a href="{{ route('tag.index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Back</a>
          </div>
        </div>
        <div class="card-body p-0">
            @if($errors->any())
                <div class="alert alert-danger mx-3">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="mx-3 mt-2" action="{{ route('tag.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Tag Name</label>
                    <input type="text" name="name" id="name" class="form-control" placeholder="Please Insert Tag Name" maxlength="20" required value="{{ old('name') }}">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Save Tag</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/tag/edit.blade.php
@extends('layouts.admin')

@section('title', 'Tag')

@section('header')
    <h1>Tag</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>Edit Tag</h4>
          <div class="card-header-action">
            <a href="{{ route('tag.index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Back</a>
          </div>
        </div>
        <div class="card-body p-0">
            @if($errors->any())
                <div class="alert alert-danger mx-3">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="mx-3 mt-2" action="{{ route('tag.update', $tag->id) }}" method="POST">
                @csrf
                @method('PUT')

                <div class="form-group">
                    <label for="name">Tag Name</label>
                    <input type="text" name="name" id="name" class="form-control" placeholder="Please Insert Tag Name" value="{{ $tag->name }}" maxlength="20" required>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-warning">Update Tag</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.admin')

@section('title', 'Tag')

@section('header')
    <h1>Tag</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>List Tag</h4>
          <div class="card-header-action">
            <a href="{{ route('tag.create') }}" class="btn btn-primary">Add Tag <i class="fas fa-chevron-right"></i></a>
          </div>
        </div>
        <div class="card-body p-0">
          <div class="table-responsive table-invoice">
            <table class="table table-striped">
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Slug</th>
                <th>Action</th>
              </tr>
              @forelse ($tags as $tag)
              <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $tag->name }}</td>
                <td>{{ $tag->slug }}</td>
                <td>
                    <form action="{{ route('tag.destroy', $tag->id) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <a href="{{ route('tag.edit', $tag->id) }}" class="btn btn-warning">Edit</a>
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure ?')">Delete</button>
                    </form>
                </td>
              </tr>
              @empty
              <tr>
                  <td colspan="12"><p class="text-center text-danger mt-3"><strong>Data Empty !</strong></p></td>
              </tr>
              @endforelse
            </table>
            {{ $tags->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    @include('sweetalert::alert')
    <script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>
@endpush