routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [BlogController::class, 'index'])->name('blog');
Route::get('/article/{slug}', [BlogController::class, 'isi_blog'])->name('isi_blog');
Route::get('/search', [BlogController::class, 'cari'])->name('cari');



Auth::routes();

Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::get('/post/deleted', [PostController::class, 'delete_show'])->name('post.deleted');
    Route::get('/post/restore/{id}', [PostController::class, 'restore'])->name('post.restore');
    Route::delete('/post/delete-permanent/{id}', [PostController::class, 'kill'])->name('post.kill');

    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    Route::resource('user', UserController::class);
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/{slug}', [BlogController::class, 'kategori'])->name('kategori');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function post()
    {
        return $this->hasMany(Post::class, 'user_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Rules\MatchOldPassword;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Paginator::useBootstrap();
        $users = User::where('id', '!=', Auth::user()->id)->latest()->paginate(10);
        return view('admin.user.index', compact('users'))->with('i');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:50|string|min:3',
            'email' => 'required|email|max:50|unique:users|min:3',
            'password' => 'required|max:50|min:8|confirmed',
            'password_confirmation' => 'same:password',
            'role' => 'required'
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'role' => $request->role
        ]);

        return redirect()->route('user.index')->withSuccess('User successfully created !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $this->validate($request, [
            'name' => 'required|max:50|string|min:3',
            'email' => 'required|email|max:50|min:3|unique:users,email,'.$user->id,
            // 'current_password' => new MatchOldPassword,
            // 'new_password' => 'max:50|min:8',
            // 'new_confirm_password' => 'same:new_password',
            'role' => 'required'
        ]);

        // if($request->input('new_password') && $request->input('new_confirm_password') && $request->input('current_password'))
        // {
        //     $input_user = [
        //         'name' => $request->name,
        //         'email' => $request->email,
        //         'password' => Hash::make($request->new_password),
        //         'role' => $request->role
        //     ];
        // }else {
        //     $input_user = [
        //         'name' => $request->name,
        //         'email' => $request->email,
        //         'role' => $request->role
        //     ];
        // }

        $input_user = [
            'name' => $request->name,
            'email' => $request->email,
            'role' => $request->role
        ];

        $user->update($input_user);

        return redirect()->route('user.index')->withSuccess('User successfully updated !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('user.index')->withSuccess('User successfully deleted !');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('title', 'User')

@section('header')
    <h1>User</h1>
@endsection
@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>Add User</h4>
          <div class="card-header-action">
            <a href="{{ route('user.index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Back</a>
          </div>
        </div>
        <div class="card-body p-0">
            @if($errors->any())
                <div class="alert alert-danger mx-3">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="mx-3 mt-2" action="{{ route('user.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" placeholder="Please Insert Name" maxlength="50" required value="{{ old('name') }}">
                    @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror" placeholder="Please Insert Email" maxlength="50" required value="{{ old('email') }}">
                    @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="role">Role User</label>
                    <select class="form-control select2" name="role" id="role">
                        <option value="" selected disabled>Pilih Role User</option>
                        <option value="0">Author</option>
                        <option value="1">Admin</option>
                    </select>
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" class="form-control @error('password') is-invalid @enderror" placeholder="Please Insert Password" maxlength="50" required>
                        @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                        @enderror
                    </div>
                    <div class="form-group col-md-6">
                        <label for="password_confirmation">Confirm Password</label>
                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" placeholder="Please Insert Confirm Password" maxlength="50" required>
                    </div>
                </div>

                <div class="form-group form-check">
                    <input class="form-check-input" id="showpw" type="checkbox" onclick="showPw()">
                    <label class="form-check-label" for="showpw">Show Password</label>
                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-success">Save User</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
  <script>
    function showPw() {
        var x = document.getElementById("password");
        var y = document.getElementById("password_confirmation");
        if (x.type && y.type === "password") {
            x.type = "text";
            y.type = "text";
        } else {
            x.type = "password";
            y.type = "password";
        }
    }
  </script>
@endpush

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('title', 'User')

@section('header')
    <h1>User</h1>
@endsection
@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>Add User</h4>
          <div class="card-header-action">
            <a href="{{ route('user.index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Back</a>
          </div>
        </div>
        <div class="card-body p-0">
            @if($errors->any())
                <div class="alert alert-danger mx-3">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="mx-3 mt-2" action="{{ route('user.update', $user->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" placeholder="Please Insert Name" maxlength="50" required value="{{ $user->name }}">
                    @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror" placeholder="Please Insert Email" maxlength="50" required value="{{ $user->email }}">
                    @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="role">Role User</label>
                    <select class="form-control select2" name="role" id="role">
                        <option value="0" @if($user->role == 0) selected @endif>Author</option>
                        <option value="1" @if($user->role == 1) selected @endif>Admin</option>
                    </select>
                </div>

                {{-- <div class="form-group">
                    <label for="current_password">Old Password</label>
                    <input type="password" name="current_password" id="current_password" class="form-control @error('current_password') is-invalid @enderror" placeholder="Please Insert Current Password" maxlength="50">
                    @error('current_password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="new_password">Password</label>
                        <input type="password" name="new_password" id="new_password" class="form-control @error('new_password') is-invalid @enderror" placeholder="Please Insert New Password" maxlength="50">
                        @error('new_password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                        @enderror
                    </div>
                    <div class="form-group col-md-6">
                        <label for="new_confirm_password">Confirm Password</label>
                        <input type="password" name="new_confirm_password" id="new_confirm_password" class="form-control" placeholder="Please Insert New Confirm Password" maxlength="50">
                    </div>
                </div> --}}

                {{-- <div class="form-group form-check">
                    <input class="form-check-input" id="showpw" type="checkbox" onclick="showPw()">
                    <label class="form-check-label" for="showpw">Show Password</label>
                </div> --}}


                <div class="form-group">
                    <button type="submit" class="btn btn-warning">Update User</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
  <script>
    function showPw() {
        var x = document.getElementById("new_password");
        var y = document.getElementById("new_confirm_password");
        var z = document.getElementById("current_password");
        if (x.type && y.type && z.type === "password") {
            x.type = "text";
            y.type = "text";
            z.type = "text";
        } else {
            x.type = "password";
            y.type = "password";
            z.type = "password";
        }
    }
  </script>
@endpush

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('title', 'User')

@section('header')
    <h1>User</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4>List User</h4>
          <div class="card-header-action">
            <a href="{{ route('user.create') }}" class="btn btn-primary">Add User <i class="fas fa-chevron-right"></i></a>
          </div>
        </div>
        <div class="card-body p-0">
          <div class="table-responsive table-invoice">
            <table class="table table-striped">
              <tr>
                <th>#</th>
                <th>Nama User</th>
                <th>Email</th>
                <th>Role</th>
                <th>Action</th>
              </tr>
              @forelse ($users as $user)
              <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    @if($user->role == 1)
                        <span class="badge badge-success">Admin</span>
                    @else
                        <span class="badge badge-info">Author</span>
                    @endif
                </td>
                <td>
                    <form action="{{ route('user.destroy', $user->id) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <a href="{{ route('user.edit', $user->id) }}" class="btn btn-warning">Edit</a>
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure ?')">Delete</button>
                    </form>
                </td>
              </tr>
              @empty
              <tr>
                  <td colspan="12"><p class="text-center text-danger mt-3"><strong>Data Empty !</strong></p></td>
              </tr>
              @endforelse
            </table>
            {{ $users->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    @include('sweetalert::alert')
    <script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>
@endpush